# -*- coding: utf-8 -*-
"""BMI_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FUPVQUfuwxfi0AKawyUSIr9dJCOtG1e
"""

import streamlit as st
import pandas as pd

st.title("BMI CALCULATOR")

h = st.slider("Enter your height (in cm):",100,250,175)
w = st.slider("Enter your weight (in kg): ", 40,200,70)

bmi = w/((h/100) ** 2)

st.write(f"Your BMI is {bmi:.2f}")
st.write("### BMI Categories ###")
st.write("- Underweight: BMI less than 18.5")
st.write("- Normal weight: BMI between 18.5 and 24.9")
st.write("- Overweight: BMI between 25 and 29.9")
st.write("- Obesity: BMI 30 or greater")

