# -*- coding: utf-8 -*-
"""PomodoroTimer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_nEphCXSgip9f9X0OmNhSTZahiTosUrN
"""

import streamlit as st
import time

st.title("Pomodoro Timer")
work_time  = st.slider("Work Time (minutes)", 5, 90, 25)
break_time  = st.slider("Break Time (minutes)", 1, 30, 5)

def pomodoro_timer(work_time, break_time):
  work_seconds = work_time * 60
  break_seconds  = break_time*60

  work_placeholder = st.empty()
  break_placeholder = st.empty()

  work_placeholder.write("Work!")
  for i in range(work_seconds):
    time.sleep(1)
    work_placeholder.write(f"Work! {work_seconds-i} seconds left")

  break_placeholder.write("Break!")
  for i in range(break_seconds):
    time.sleep(1)
    break_placeholder.write(f"Break! {break_seconds-i} seconds left")

if st.button("Start Timer"):
  pomodoro_timer(work_time,break_time)

